name: 2025_Optimizing_Phase_Mask
channels:
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - matplotlib
  - notebook
  - numpy
  - anaconda::scikit-image
  - conda-forge::opencv
  - conda-forge::mayavi
